<?php
// $Id: xoops_version.php,v 0.0.1 2005/10/24 20:30:00 domifara Exp $
/**
 * $Id: xoops_version.php v 1.5 23 August 2004 hsalazar Exp $
 * Module: Soapbox
 * Version: v 1.5
 * Release Date: 23 August 2004
 * Author: hsalazar
 * Licence: GNU
 */
if ( !defined("XOOPS_MAINFILE_INCLUDED") || !defined("XOOPS_ROOT_PATH") || !defined("XOOPS_URL") ) {
	exit();
}
$modversion['name'] = _MI_SB_MD_NAME;
$modversion['version'] = 1.60; //original ver1.5RC3 FIX by domifara
$modversion['description'] = _MI_SB_MD_DESC;
$modversion['author'] = "hsalazar, domifara";
$modversion['credits'] = "Catzwolf";
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['help'] = 'page=help';
$modversion['official'] = 0;
$modversion['image'] = "images/sb_slogo.png";
$modversion['dirname'] = "soapbox";

$modversion['author_realname'] = "Horacio Salazar, domifara";
$modversion['author_website_url'] = "http://www.anacronista.com, http://domifara.lolipop.jp/xo/";
$modversion['author_website_name'] = "Anacronista, DomifaraOOP";
$modversion['author_email'] = "hsalazar@xoops.org";
//$modversion['status'] = "Version 1.5";

$modversion['warning'] = _MI_SB_WARNING;
$modversion['author_word'] = _MI_SB_AUTHORMSG;


$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion["demo_site_url"] = '';
$modversion["demo_site_name"] = '';
$modversion["module_website_url"] = 'http://xoops.org';
$modversion["module_website_name"] = 'XOOPS';
$modversion["release"] = '0';
$modversion["module_status"] = 'Final';
$modversion['release_date'] = '2012/12/18';
$modversion['min_php'] = '5.2';
$modversion['min_xoops'] = '2.5.5';
$modversion['min_admin']='1.1';
//$modversion['min_db']= array('mysql'=>'5.0.7', 'mysqli'=>'5.0.7');


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['system_menu'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "sbcolumns";
$modversion['tables'][1] = "sbarticles";
$modversion['tables'][2] = "sbvotedata";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "sb_search";

// Menu
$modversion['hasMain'] = 1;

global $xoopsDB, $xoopsUser;
$hModule =& xoops_gethandler('module');
$i = 0 ;
if ($soapModule =& $hModule->getByDirname('soapbox')) {
	$gperm_handler = & xoops_gethandler( 'groupperm' );
	$hModConfig =& xoops_gethandler('config');

	$groups = (is_object($xoopsUser)) ? $xoopsUser -> getGroups() : XOOPS_GROUP_ANONYMOUS;

	if (is_object($xoopsUser)) {
		$user = $xoopsUser->getVar('uid');
		$query = $xoopsDB -> query ( "SELECT author FROM " . $xoopsDB -> prefix ("sbcolumns") . " WHERE author = " . $xoopsUser->getVar('uid') );
		if ($query) {
			$isauthor = $xoopsDB -> getRowsNum($query);
			if ( $xoopsUser -> isAdmin($soapModule -> getVar('mid')) || $isauthor >= 1 ) {
				$i++;
				$modversion['sub'][$i]['name'] = _MI_SB_SUB_SMNAME1;
				$modversion['sub'][$i]['url'] = "submit.php?op=add";
			}
		}
	}
	unset ($isauthor);
	$module_id = $soapModule->getVar('mid');
	$soapConfig =& $hModConfig->getConfigsByCat(0, $soapModule->getVar('mid'));
	if (isset($soapConfig['colsinmenu']) && $soapConfig['colsinmenu'] == 1 && is_object($xoopsUser)) {
		$sql = $xoopsDB->query( "SELECT columnID, name FROM " . $xoopsDB->prefix( "sbcolumns" ) . "  ORDER BY weight" );
		if ($sql) {
			while (list($columnID, $name) = $xoopsDB->fetchRow($sql)) {
				if ($gperm_handler->checkRight('Column Permissions', $columnID, $groups, $module_id)) {
					$i++;
					$modversion['sub'][$i]['name'] = $name;
					$modversion['sub'][$i]['url'] = "column.php?columnID=" . $columnID . "";
				} 
			} 
		}
	}
}

$i=0;
$modversion['blocks'][$i]['file'] = "arts_rated.php";
$modversion['blocks'][$i]['name'] = _MI_SB_ARTSRATED;
$modversion['blocks'][$i]['description'] = _MI_SB_ARTSRATED_DSC;
$modversion['blocks'][$i]['show_func'] = "b_arts_rated";
$modversion['blocks'][$i]['edit_func'] = "b_arts_rated_edit";
$modversion['blocks'][$i]['options'] = "rating|5|65";
$modversion['blocks'][$i]['template'] = "arts_rated.html";
$modversion['blocks'][$i]['can_clone'] = true ;
$i++;
$modversion['blocks'][$i]['file'] = "arts_new.php";
$modversion['blocks'][$i]['name'] = _MI_SB_ARTSNEW;
$modversion['blocks'][$i]['description'] = _MI_SB_ARTSNEW_DSC;
$modversion['blocks'][$i]['show_func'] = "b_arts_new_show";
$modversion['blocks'][$i]['edit_func'] = "b_arts_new_edit";
$modversion['blocks'][$i]['options'] = "datesub|5|65";
$modversion['blocks'][$i]['template'] = "arts_new.html";
$modversion['blocks'][$i]['can_clone'] = true ;
$i++;
$modversion['blocks'][$i]['file'] = "arts_top.php";
$modversion['blocks'][$i]['name'] = _MI_SB_ARTSTOP;
$modversion['blocks'][$i]['description'] = _MI_SB_ARTSTOP_DSC;
$modversion['blocks'][$i]['show_func'] = "b_arts_top_show";
$modversion['blocks'][$i]['edit_func'] = "b_arts_top_edit";
$modversion['blocks'][$i]['options'] = "counter|5|65";
$modversion['blocks'][$i]['template'] = "arts_top.html";
$modversion['blocks'][$i]['can_clone'] = true ;
$i++;
$modversion['blocks'][$i]['file'] = "arts_spot.php";
$modversion['blocks'][$i]['name'] = _MI_SB_ARTSPOTLIGHT;
$modversion['blocks'][$i]['description'] = _MI_SB_ARTSPOTLIGHT_DSC;
$modversion['blocks'][$i]['show_func'] = "b_arts_spot_show";
$modversion['blocks'][$i]['edit_func'] = "b_arts_spot_edit";
$modversion['blocks'][$i]['options'] = "1|5|1|1|1|ver|1|datesub|65|0";
$modversion['blocks'][$i]['template'] = "arts_spot.html";
$modversion['blocks'][$i]['can_clone'] = true ;
$i++;
$modversion['blocks'][$i]['file'] = "columns_spot.php";
$modversion['blocks'][$i]['name'] = _MI_SB_ARTSPOTLIGHT2;
$modversion['blocks'][$i]['description'] = _MI_SB_ARTSPOTLIGHT2_DSC;
$modversion['blocks'][$i]['show_func'] = "b_columns_spot_show";
$modversion['blocks'][$i]['edit_func'] = "b_columns_spot_edit";
$modversion['blocks'][$i]['options'] = "1|5|1|1|1|ver|1|datesub|65|0";
$modversion['blocks'][$i]['template'] = "columns_spot.html";
$modversion['blocks'][$i]['can_clone'] = true ;

// Templates
$modversion['templates'][1]['file'] = 'sb_column.html';
$modversion['templates'][1]['description'] = 'Display columns';
$modversion['templates'][2]['file'] = 'sb_index.html';
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = 'sb_article.html';
$modversion['templates'][3]['description'] = 'Display article';

// Config Settings (only for modules that need config settings generated automatically)
$i=0;
$modversion['config'][$i]['name'] = 'allowsubmit';
$modversion['config'][$i]['title'] = '_MI_SB_ALLOWSUBMIT';
$modversion['config'][$i]['description'] = '_MI_SB_ALLOWSUBMITDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'autoapprove';
$modversion['config'][$i]['title'] = '_MI_SB_AUTOAPPROVE';
$modversion['config'][$i]['description'] = '_MI_SB_AUTOAPPROVEDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'adminhits';
$modversion['config'][$i]['title'] = '_MI_SB_ALLOWADMINHITS';
$modversion['config'][$i]['description'] = '_MI_SB_ALLOWADMINHITSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'perpage';
$modversion['config'][$i]['title'] = '_MI_SB_PERPAGE';
$modversion['config'][$i]['description'] = '_MI_SB_PERPAGEDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 5;
$modversion['config'][$i]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );
$i++;
$modversion['config'][$i]['name'] = 'indexperpage';
$modversion['config'][$i]['title'] = '_MI_SB_PERPAGEINDEX';
$modversion['config'][$i]['description'] = '_MI_SB_PERPAGEINDEXDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 5;
$modversion['config'][$i]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );
$i++;
$modversion['config'][$i]['name'] = 'sbimgdir';
$modversion['config'][$i]['title'] = '_MI_SB_IMGDIR';
$modversion['config'][$i]['description'] = '_MI_SB_IMGDIRDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'modules/soapbox/images';
$i++;
$modversion['config'][$i]['name'] = 'sbuploaddir';
$modversion['config'][$i]['title'] = '_MI_SB_UPLOADDIR';
$modversion['config'][$i]['description'] = '_MI_SB_UPLOADDIRDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'modules/soapbox/images/uploads';
$i++;
$modversion['config'][$i]['name'] = 'maximgwidth';
$modversion['config'][$i]['title'] = '_MI_SB_IMGWIDTH';
$modversion['config'][$i]['description'] = '_MI_SB_IMGWIDTHDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 800;
$i++;
$modversion['config'][$i]['name'] = 'maximgheight';
$modversion['config'][$i]['title'] = '_MI_SB_IMGHEIGHT';
$modversion['config'][$i]['description'] = '_MI_SB_IMGHEIGHTDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 800;
$i++;
$modversion['config'][$i]['name'] = 'maxfilesize';
$modversion['config'][$i]['title'] = '_MI_SB_MAXFILESIZE';
$modversion['config'][$i]['description'] = '_MI_SB_MAXFILESIZEDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 250000;
$i++;
$modversion['config'][$i]['name'] = 'dateformat';
$modversion['config'][$i]['title'] = '_MI_SB_DATEFORMAT';
$modversion['config'][$i]['description'] = '_MI_SB_DATEFORMATDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _SHORTDATESTRING; //'d M Y';
$i++;
$modversion['config'][$i]['name'] = 'globaldisplaycomments';
$modversion['config'][$i]['title'] = '_MI_SB_ALLOWCOMMENTS';
$modversion['config'][$i]['description'] = '_MI_SB_ALLOWCOMMENTSDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'morearts';
$modversion['config'][$i]['title'] = '_MI_SB_MOREARTS';
$modversion['config'][$i]['description'] = '_MI_SB_MOREARTSDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['options'] = array( '3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20 );
$i++;
$modversion['config'][$i]['name'] = 'colsinmenu';
$modversion['config'][$i]['title'] = '_MI_SB_COLSINMENU';
$modversion['config'][$i]['description'] = '_MI_SB_COLSINMENUDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;
$i++;
$modversion['config'][$i]['name'] = 'colsperindex';
$modversion['config'][$i]['title'] = '_MI_SB_COLSPERINDEX';
$modversion['config'][$i]['description'] = '_MI_SB_COLSPERINDEXDSC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['options'] = array( '3' => 3, '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );
$i++;
$modversion['config'][$i]['name'] = 'includerating';
$modversion['config'][$i]['title'] = '_MI_SB_ALLOWRATING';
$modversion['config'][$i]['description'] = '_MI_SB_ALLOWRATINGDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$i++;
$modversion['config'][$i]['name'] = 'introtitle';
$modversion['config'][$i]['title'] = '_MI_SB_INTROTIT';
$modversion['config'][$i]['description'] = '_MI_SB_INTROTITDSC';
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _MI_SB_INTROTITDFLT;
$i++;
$modversion['config'][$i]['name'] = 'introtext';
$modversion['config'][$i]['title'] = '_MI_SB_INTROTEXT';
$modversion['config'][$i]['description'] = '_MI_SB_INTROTEXTDSC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = _MI_SB_INTROTEXTDFLT;
$i++;
$modversion['config'][$i]['name'] = 'buttonsadmin';
$modversion['config'][$i]['title'] = '_MI_SB_BUTTSTXT';
$modversion['config'][$i]['description'] = '_MI_SB_BUTTSTXTDSC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

//$modversion['config'][] = array(
//	'name' => 'form_options',
//	'title' => '_MI_SB_FORM_OPTIONS',
//	'description' => '_MI_SB_FORM_OPTIONS_DESC',
//	'formtype' => 'select',
//	'valuetype' => 'text',
//	'options' => array(
//					_MI_SB_FORM_DHTML=>'dhtml',
//					_MI_SB_FORM_COMPACT=>'textarea',
//					_MI_SB_FORM_SPAW=>'spaw',
//					_MI_SB_FORM_HTMLAREA=>'htmlarea',
//					_MI_SB_FORM_KOIVI=>'koivi',
//					_MI_SB_FORM_TINYMCE=>'tinymce',
//					_MI_SB_FORM_FCK=>'fck'),
//	'default' =>'dhtml');

$i++;
$modversion['config'][$i]['name'] = 'form_options';
$modversion['config'][$i]['title'] = '_MI_SB_FORM_OPTIONS';
$modversion['config'][$i]['description'] = '_MI_SB_FORM_OPTIONS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'dhtml';
xoops_load('xoopseditorhandler');
$editor_handler = XoopsEditorHandler::getInstance();
$modversion['config'][$i]['options'] = array_flip($editor_handler->getList());



// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'articleID';
$modversion['comments']['pageName'] = 'article.php';

// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'sb_com_approve';
$modversion['comments']['callback']['update'] = 'sb_com_update';

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'sb_notify_iteminfo';
$i=0;
$modversion['notification']['category'][$i]['name'] = 'global';
$modversion['notification']['category'][$i]['title'] = _MI_SB_GLOBAL_NOTIFY;
$modversion['notification']['category'][$i]['description'] = _MI_SB_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][$i]['subscribe_from'] = array( 'index.php', 'column.php', 'article.php' );
$i++;
$modversion['notification']['category'][$i]['name'] = 'column';
$modversion['notification']['category'][$i]['title'] = _MI_SB_COLUMN_NOTIFY;
$modversion['notification']['category'][$i]['description'] = _MI_SB_COLUMN_NOTIFYDSC;
$modversion['notification']['category'][$i]['subscribe_from'] = array( 'index.php' );
$modversion['notification']['category'][$i]['item_name'] = 'columnID';
$modversion['notification']['category'][$i]['allow_bookmark'] = 1;
$i++;
$modversion['notification']['category'][$i]['name'] = 'article';
$modversion['notification']['category'][$i]['title'] = _MI_SB_ARTICLE_NOTIFY;
$modversion['notification']['category'][$i]['description'] = _MI_SB_ARTICLE_NOTIFYDSC;
$modversion['notification']['category'][$i]['subscribe_from'] = 'article.php';
$modversion['notification']['category'][$i]['item_name'] = 'articleID';
$modversion['notification']['category'][$i]['allow_bookmark'] = 1;

$i=0;
$modversion['notification']['event'][$i]['name'] = 'new_column';
$modversion['notification']['event'][$i]['category'] = 'global';
$modversion['notification']['event'][$i]['title'] = _MI_SB_GLOBAL_NEWCOLUMN_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_GLOBAL_NEWCOLUMN_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_GLOBAL_NEWCOLUMN_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_newcolumn_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_GLOBAL_NEWCOLUMN_NOTIFYSBJ;
$i++;
$modversion['notification']['event'][$i]['name'] = 'article_submit';
$modversion['notification']['event'][$i]['category'] = 'global';
$modversion['notification']['event'][$i]['admin_only'] = 1;
$modversion['notification']['event'][$i]['title'] = _MI_SB_GLOBAL_ARTICLESUBMIT_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_GLOBAL_ARTICLESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_GLOBAL_ARTICLESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_articlesubmit_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_GLOBAL_ARTICLESUBMIT_NOTIFYSBJ;
$i++;
$modversion['notification']['event'][$i]['name'] = 'new_article';
$modversion['notification']['event'][$i]['category'] = 'global';
$modversion['notification']['event'][$i]['title'] = _MI_SB_GLOBAL_NEWARTICLE_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_GLOBAL_NEWARTICLE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_GLOBAL_NEWARTICLE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'global_newarticle_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_GLOBAL_NEWARTICLE_NOTIFYSBJ;
$i++;
$modversion['notification']['event'][$i]['name'] = 'article_submit';
$modversion['notification']['event'][$i]['category'] = 'column';
$modversion['notification']['event'][$i]['admin_only'] = 1;
$modversion['notification']['event'][$i]['title'] = _MI_SB_COLUMN_ARTICLESUBMIT_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_COLUMN_ARTICLESUBMIT_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_COLUMN_ARTICLESUBMIT_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'column_articlesubmit_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_COLUMN_ARTICLESUBMIT_NOTIFYSBJ;
$i++;
$modversion['notification']['event'][$i]['name'] = 'new_article';
$modversion['notification']['event'][$i]['category'] = 'column';
$modversion['notification']['event'][$i]['title'] = _MI_SB_COLUMN_NEWARTICLE_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_COLUMN_NEWARTICLE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_COLUMN_NEWARTICLE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'column_newarticle_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_COLUMN_NEWARTICLE_NOTIFYSBJ;
$i++;
$modversion['notification']['event'][$i]['name'] = 'approve';
$modversion['notification']['event'][$i]['category'] = 'article';
$modversion['notification']['event'][$i]['invisible'] = 1;
$modversion['notification']['event'][$i]['title'] = _MI_SB_ARTICLE_APPROVE_NOTIFY;
$modversion['notification']['event'][$i]['caption'] = _MI_SB_ARTICLE_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][$i]['description'] = _MI_SB_ARTICLE_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][$i]['mail_template'] = 'article_approve_notify';
$modversion['notification']['event'][$i]['mail_subject'] = _MI_SB_ARTICLE_APPROVE_NOTIFYSBJ;

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}